spring.application.name=API


# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_db
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect